[category.test]
description = "foo"

[command.command]
hybrid=true
name = "coomandfuckyou"
description = "command description woo hoo!"
aliases = ['cmd', 'hiliz']

[command.group]
hybrid=true
name='assgroup'
description = "group description"
parent='command'

[command.child]
hybrid=true
name='thefuckingchild'
description = "child command"
parent = "group"