name = "config-parser-bot"
version = "1.0.0a"
description = "A bot that's just a default ass bot, but uses a config file to set up command things. This is more about the parsing part of things than the bot itself."
license = "MIT"
authors = [
    "Cyrus (cyrus01337)",
    "Leonardo (LeoCx1000)"
]
readme = "README.md"
homepage = "https://github.com/discordpy-cursed/config-parser-bot"
documentation = "https://github.com/discordpy-cursed/config-parser-bot/blob/main/README.md"

[tool.black.dependencies]
python = "^3.11"

[tool.black]
line-length = 125
skip-string-normalization = true

[tool.isort]
combine_as_imports = true
combine_star = true
line_length = 125
profile = "black"

[tool.pyright]
pythonversion = "^3.11"
