[category.test]
description = "foo"

[command.command]
name = "coomand"
description = "command description"
aliases = ['cmd']

[command.group]
description = "group description"

[command.child]
description = "child command"
enabled = false
parent = "group"

[default-values.command]
enabled = true
hidden = false
description = "No description provided..."

[default-values.category]
description = 'No description provided...'