name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Build Dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -rU requirements.dev.txt

      - name: Sort Imports with isort
        run: |
          python -m isort --check . --profile black
          python -m isort . --profile black
        continue-on-error: true

      - name: Auto-format with Black
        run: |
          python -m black --check
          python -m black
        continue-on-error: true
