name: Pipeline

on:
  push:
    branches: [main]

jobs:
  Pipeline:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -Ur requirements.txt -r requirements.dev.txt

      - name: Sort Imports with isort
        run: |
          isort -qc --show-files --profile black .
          isort -qc --profile black .
        continue-on-error: true

      - name: Auto-format with Black
        run: |
          black --check .
          black .
        continue-on-error: true

      - name: Lint with Pyright
        run: pyright --lib --warnings .
